toolkit:
  mode: monorepo
  phase:
    enabled: false
    pattern: "^phase-[0-9]+$"
    tagPrefix: ""

commit:
  types:
    allowed:
      - feat
      - fix
      - docs
      - test
      - refactor
      - chore
      - style

  scopes:
    allowed:
      - context
      - core
      - driver
      - api
      - ci
      - repo
      - tooling

    meta:
      - release
      - build
      - ci
      - tooling

release:
  dryRun: false

  breakingChange:
    keyword: "BREAKING CHANGE"

  semanticGroups:
    feat: "🚀 Features"
    fix: "🐞 Bug Fixes"
    docs: "📚 Documentation"
    test: "🧪 Tests"
    refactor: "♻️ Refactoring"
    chore: "🔧 Chores"
    style: "🎨 Style"

  versionBumpRules:
    feat: minor
    fix: patch
    refactor: patch
    docs: none
    test: none
    chore: none
    style: none

  tagFormat: "{package}-v{version}"

packages:
  api:
    versionFile: "packages/api/VERSION"
  core:
    versionFile: "packages/core/VERSION"

version:
  rootFile: "VERSION"
