name: Commit Message Check

permissions:
  contents: write

env:
  TOOLKIT_ROOT: tools/git/git-toolkit
  TOOLKIT_SCRIPTS: tools/git/git-toolkit/scripts

on:
  pull_request:
  push:
    branches: [master]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup script permissions
        run: |
          find "${{ env.TOOLKIT_SCRIPTS }}" -type f -name "*.sh" -exec chmod +x {} \;

      - name: Verify commit message
        run: |
          "${{ env.TOOLKIT_SCRIPTS }}/verify-commit-message.sh"
